const E=Arcana, app=document.querySelector('#app'),modal=document.querySelector('#modal');let g=null,screen='menu',settings={sound:true,music:false},stats={wins:0,best:0},audio=null,musicTimer=null;
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
settings={...settings,...read('arcana-settings',{})};stats={...stats,...read('arcana-stats',{})};
if(!Number.isInteger(stats.wins)||stats.wins<0)stats.wins=0;if(!Number.isFinite(stats.best)||stats.best<0)stats.best=0;
let stored=read('arcana-save',null);if(E.valid(stored))g=stored;
function store(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function save(){if(g&&!store('arcana-save',g))g.log='Przeglądarka blokuje zapis. Rozgrywka działa, ale nie przetrwa zamknięcia.';store('arcana-stats',stats);store('arcana-settings',settings)}
function tone(freq=500,duration=.1,volume=.035){if(!settings.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),v=audio.createGain();o.type='sine';o.frequency.value=freq;v.gain.setValueAtTime(volume,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(v).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function music(){clearInterval(musicTimer);musicTimer=null;if(settings.music&&screen!=='menu'&&!document.hidden){let i=0;musicTimer=setInterval(()=>{const sound=settings.sound;settings.sound=true;tone([130.81,164.81,196,164.81][i++%4],1.3,.008);settings.sound=sound},1600)}}
const btn=(label,action,cls='',disabled=false)=>`<button class="${cls}" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
function header(){return `<div class="top"><div class="brand">♧ ARCANA POKER</div><div class="row">${btn('Układy','rules')}${btn('Ustawienia','settings')}${screen!=='menu'?btn('Pauza / Menu','menu'):''}</div></div>`}
function render(){app.innerHTML=header();if(screen==='menu'){app.innerHTML+=`<section class="hero"><div class="eyebrow">Strategia • Układy • Synergie</div><div class="mark">♠ ♦ ♣ ♥</div><h1>Każda ręka.<br>Nowa szansa.</h1><p>Buduj układy pokerowe, zbieraj magiczne karty i pokonaj osiem prób. Żadnych zakładów — liczą się punkty i pomysł.</p><div class="row">${btn('Nowa wyprawa','new','primary')}${btn('Kontynuuj','continue','',!g)}</div><p class="muted">Najlepsza ręka: ${stats.best} pkt • Ukończone wyprawy: ${stats.wins}</p></section>`;return;}
 const side=`<aside class="sidebar panel"><div class="eyebrow">Twoja kolekcja ${g.arcana.length}/5</div><h2>Arcana</h2>${g.arcana.map((id,i)=>{const a=E.ARCANA.find(a=>a.id===id);return `<div class="arcana"><strong>${i+1}. ${a.name}</strong><p>${a.desc}</p>${g.phase==='shop'?btn('↑ Przesuń','up:'+id,'',i===0)+btn('Sprzedaj +'+Math.floor(a.cost/2)+' ◈','sell:'+id):''}</div>`}).join('')||'<p class="muted">Kup pierwszą kartę po wygraniu rundy. Efekty działają od góry do dołu.</p>'}<p class="muted">Najlepsza ręka tej wyprawy: ${g.bestHand}</p></aside>`;
 const statsBar=`<div class="panel"><div class="stats"><div class="stat"><small>ETAP</small><strong>${g.round+1} / 8</strong></div><div class="stat"><small>PUNKTY / CEL</small><strong>${g.score} / ${E.TARGETS[g.round]}</strong></div><div class="stat"><small>RĘCE / WYMIANY</small><strong>${g.hands} / ${g.discards}</strong></div><div class="stat"><small>MONETY</small><strong>${g.money} ◈</strong></div></div><div class="progress"><i style="width:${Math.min(100,g.score/E.TARGETS[g.round]*100)}%"></i></div></div>`;
 app.innerHTML+=statsBar+`<div class="table">${side}<section class="panel" id="board">`;
 const board=document.querySelector('#board');
 if(g.phase==='play'){const p=E.preview(g,g.selected.map(i=>g.hand[i]));board.innerHTML=`<div class="eyebrow">${g.round===2?'PRÓBA: −2 bazowego mnożnika':g.round===5?'PRÓBA: −20 bazowych żetonów':g.round===7?'FINAŁ: 15 000 punktów':'STÓŁ • TALIA '+g.deck.length+' KART'}</div><div class="calc">${p?`${p.name} • poziom ${g.levels[p.type]}<br><strong>${p.chips} × ${p.mult} = ${p.total}</strong>`:'Wybierz od 1 do 5 kart<br><strong>Twój następny ruch</strong>'}</div><div class="hand">${g.hand.map((c,i)=>`<button class="card ${c.s<2?'red':''} ${g.selected.includes(i)?'selected':''}" data-action="card:${i}" aria-label="${rank(c.r)} ${['kier','karo','trefl','pik'][c.s]}" aria-pressed="${g.selected.includes(i)}"><span>${rank(c.r)}</span><span class="suit">${['♥','♦','♣','♠'][c.s]}</span><span class="bottom">${rank(c.r)}</span></button>`).join('')}</div><p class="muted">Zaznaczono ${g.selected.length}/5 • Punktują tylko karty tworzące układ.</p><div class="row">${btn('Zagraj rękę','play','primary',!g.selected.length)}${btn('Wymień ('+g.discards+')','discard','',!g.selected.length||!g.discards)}${btn('Sortuj','sort')}</div><p class="log" role="status">${g.log}</p>`;}
 else if(g.phase==='shop'){board.innerHTML=`<div class="eyebrow">RUNDA WYGRANA</div><h2>Pracownia Arcana</h2><p class="log">${g.log}</p><div class="shopgrid">${g.shop.map(id=>{const a=E.ARCANA.find(a=>a.id===id);return `<div class="arcana"><div class="symbol">✦</div><strong>${a.name}</strong><p>${a.desc}</p>${btn('Kup • '+a.cost+' ◈','buy:'+id,'primary',g.money<a.cost||g.arcana.length>=5)}</div>`}).join('')}</div><div class="arcana"><strong>Atlas: ${E.NAMES[g.planet]}</strong><p>Poziom ${g.levels[g.planet]} → ${g.levels[g.planet]+1}. +15 bazowych żetonów i +1 bazowego mnożnika.</p>${btn('Ulepsz • 3 ◈','planet','',g.money<3||g.planetBought)}</div><div class="row">${btn('Nowe oferty • '+(2+g.refreshes)+' ◈','refresh','',g.money<2+g.refreshes)}${btn('Następna runda →','next','primary')}</div>`;}
 else board.innerHTML=`<div class="hero" style="margin:25px auto"><div class="mark">${g.phase==='win'?'✦':'♠'}</div><h2>${g.phase==='win'?'Wyprawa ukończona!':'Ta wyprawa dobiegła końca'}</h2><p>${g.log}</p><p>Etap ${g.round+1}/8 • ${g.score}/${E.TARGETS[g.round]} punktów</p><div class="row">${btn('Nowa wyprawa','new','primary')}${btn('Menu','menu')}</div></div>`;
 app.innerHTML+=`<p class="footer">Oryginalna gra strategiczna • Zapis automatyczny • Web działa bez konta</p>`;
}
function rank(r){return ({11:'J',12:'Q',13:'K',14:'A'})[r]||r}
function show(html){modal.innerHTML=html+`<div class="row">${btn('Zamknij','close','primary')}</div>`;modal.showModal()}
function rules(){show(`<h2>Jak grać</h2><p>1. Wybierz 1–5 z ośmiu kart. Zagraj układ, aby zdobyć punkty: <b>żetony × mnożnik</b>. Masz 4 ręce i 3 wymiany na rundę.</p><p>2. Tylko karty tworzące układ dodają wartości: A=11, J/Q/K=10, pozostałe według numeru. Przy wysokiej karcie punktuje najwyższa karta. Strit i kolor wymagają 5 kart. A może być niskie w A–2–3–4–5.</p><p>3. W sklepie kupuj Arcana (maks. 5). Efekty działają kolejno od góry do dołu, więc po ×2 kolejna premia jest dodawana do podwojonego mnożnika. Sprzedaż daje połowę ceny.</p><p>4. Nagroda za rundę: 5 monet + niewykorzystane ręce + odsetki (1 za każde 5 monet, maks. 5). Atlas wzmacnia wybrany układ. Etapy 3 i 6 osłabiają podstawowe punktowanie.</p><table class="handtable">${E.NAMES.map((n,i)=>`<tr><td>${n}</td><td>${E.BASE[i][0]} × ${E.BASE[i][1]}</td></tr>`).join('')}</table><p>Bez zakładów i prawdziwych pieniędzy. Celem jest ukończenie 8 etapów.</p>`)}
function options(){show(`<h2>Ustawienia</h2><div class="settings">${btn('Efekty dźwiękowe: '+(settings.sound?'ON':'OFF'),'sound')}${btn('Muzyka ambient: '+(settings.music?'ON':'OFF'),'music')}${btn('Usuń zapis i rekordy','reset','danger')}</div><p>Zapis pozostaje na tym urządzeniu w tej przeglądarce. Tryb prywatny może usuwać dane po zamknięciu.</p>`)}
app.addEventListener('click',handle);modal.addEventListener('click',handle);
function handle(event){const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const [a,param]=b.dataset.action.split(':');
 if(a==='close'){modal.close();return}if(a==='rules'){rules();return}if(a==='settings'){options();return}
 if(a==='sound'||a==='music'){settings[a]=!settings[a];save();optionsRefresh();music();return}
 if(a==='reset'){if(confirm('Usunąć zapis wyprawy oraz rekordy?')){g=null;stats={wins:0,best:0};try{localStorage.removeItem('arcana-save')}catch{}save();screen='menu';modal.close();render();music()}return}
 if(a==='new'){if(g&&['play','shop'].includes(g.phase)&&!confirm('Zacząć od nowa i zastąpić zapis?'))return;g=E.newGame();screen='game';}
 else if(a==='continue'&&g)screen='game';else if(a==='menu')screen='menu';
 else if(g){if(a==='card'&&g.phase==='play'){const i=Number(param);if(g.selected.includes(i))g.selected=g.selected.filter(x=>x!==i);else if(g.selected.length<5)g.selected.push(i);tone(300+i*40)}
 else if(a==='play'){const before=g.phase;if(E.play(g)){tone(800,.2);stats.best=Math.max(stats.best,g.bestHand);if(g.phase==='win'&&before==='play')stats.wins++;}}
 else if(a==='discard')E.discard(g);else if(a==='sort'&&g.phase==='play'){g.hand.sort((a,b)=>b.r-a.r||a.s-b.s);g.selected=[];}
 else if(a==='buy')E.buy(g,param);else if(a==='sell'&&g.phase==='shop'){const j=E.ARCANA.find(x=>x.id===param);if(j&&g.arcana.includes(param)){g.money+=Math.floor(j.cost/2);g.arcana=g.arcana.filter(x=>x!==param)}}
 else if(a==='up'&&g.phase==='shop'){const i=g.arcana.indexOf(param);if(i>0)[g.arcana[i-1],g.arcana[i]]=[g.arcana[i],g.arcana[i-1]]}
 else if(a==='planet'&&g.phase==='shop'&&!g.planetBought&&g.money>=3){g.money-=3;g.levels[g.planet]++;g.planetBought=true}
 else if(a==='refresh'&&g.phase==='shop'&&g.money>=2+g.refreshes){g.money-=2+g.refreshes;g.refreshes++;E.offer(g);g.planetBought=false}
 else if(a==='next'&&g.phase==='shop'){g.round++;g.planetBought=false;E.startRound(g);}}
 save();render();if(a==='play')document.querySelector('#board')?.classList.add('burst');music();
}
function optionsRefresh(){modal.close();options()}
document.addEventListener('visibilitychange',()=>{save();music();if(document.hidden)audio?.suspend()});window.addEventListener('pagehide',save);render();
