const assert=require('node:assert/strict');const E=require('../engine.js');let n=0;function test(label,fn){fn();console.log('PASS '+label);n++}const c=(r,s=0)=>({r,s});
test('all nine hands',()=>{const hands=[[[14,0],[9,1]],[[2,0],[2,1],[8,2]],[[3,0],[3,1],[5,0],[5,1]],[[4,0],[4,1],[4,2]],[[2,0],[3,1],[4,0],[5,2],[6,3]],[[2,0],[4,0],[7,0],[9,0],[14,0]],[[2,0],[2,1],[2,2],[7,0],[7,1]],[[9,0],[9,1],[9,2],[9,3],[2,0]],[[10,1],[11,1],[12,1],[13,1],[14,1]]];hands.forEach((h,i)=>assert.equal(E.evaluate(h.map(([r,s])=>c(r,s))).type,i))});
test('ace low and duplicate ranks',()=>{assert.equal(E.evaluate([c(14),c(2,1),c(3),c(4),c(5)]).type,4);assert.equal(E.evaluate([c(2),c(3,1),c(4),c(5),c(5,1)]).type,1)});
test('pair excludes kicker, face and ace values',()=>{let g=E.newGame();assert.equal(E.preview(g,[c(2),c(2,1),c(14)]).total,28);assert.equal(E.preview(g,[c(14)]).total,16)});
test('effect order and boss',()=>{let g=E.newGame();g.arcana=['prism','spark'];const cards=[c(2),c(4),c(6),c(8),c(10)];assert.equal(E.preview(g,cards).mult,12);g.arcana.reverse();assert.equal(E.preview(g,cards).mult,16);g.round=2;assert.equal(E.preview(g,cards).mult,12)});
test('last hand multiplier preview and score',()=>{let g=E.newGame();g.hands=1;g.arcana=['last'];g.hand=[c(14),c(2,1)];g.deck=[];g.selected=[0];assert.equal(E.preview(g,[c(14)]).total,48);E.play(g);assert.equal(g.score,48);assert.equal(g.phase,'lost');assert.equal(E.play(g),false)});
test('discard prevents duplicates',()=>{let g=E.newGame();const old=g.hand.slice();g.selected=[0,1,2,3,4];E.discard(g);assert.equal(g.hand.length,8);assert.equal(g.discards,2);assert.equal(g.deck.length,39);assert(g.hand.every(x=>!old.slice(0,5).some(y=>x.r===y.r&&x.s===y.s)));assert(E.valid(g))});
test('shop buy caps and duplicate purchase',()=>{let g=E.newGame();g.phase='shop';g.money=100;g.shop=['spark'];assert(E.buy(g,'spark'));assert.equal(E.buy(g,'spark'),false);g.arcana=['spark','anvil','lone','echo','heart'];g.shop=['last'];assert.equal(E.buy(g,'last'),false)});
test('win reward once and final victory',()=>{let g=E.newGame();g.score=240;g.selected=[0];g.hand=[c(14)];g.deck=[];assert(E.play(g));assert.equal(g.phase,'shop');let money=g.money;E.play(g);assert.equal(g.money,money);g.round=7;E.startRound(g);g.score=14999;g.selected=[0];E.play(g);assert.equal(g.phase,'win')});
test('save validation rejects corruption',()=>{const g=E.newGame();assert(E.valid(JSON.parse(JSON.stringify(g))));g.hand.push(g.hand[0]);assert(!E.valid(g));assert(!E.valid({version:1}));assert(!E.valid(null))});
// Exhaustive 52 choose 5 evaluator census, canonical poker distribution.
test('exhaustive 2598960 hands',()=>{const d=[];for(let s=0;s<4;s++)for(let r=2;r<=14;r++)d.push(c(r,s));let counts=Array(9).fill(0);for(let a=0;a<48;a++)for(let b=a+1;b<49;b++)for(let c=b+1;c<50;c++)for(let d1=c+1;d1<51;d1++)for(let e=d1+1;e<52;e++)counts[E.evaluate([d[a],d[b],d[c],d[d1],d[e]]).type]++;assert.deepEqual(counts,[1302540,1098240,123552,54912,10200,5108,3744,624,40])});
console.log(n+' tests passed');
